### ISSUE TITLE
issues finding devices

### ISSUE THREAD

**Issue by mo8Zomo0** [hvanderlaan/ikea-smartlight#15]
Hi!

I would guess that it might not be an application rather then an issue with Trådfri itself.
It seems that by today they are rolling out software upgrades, I noticed some bulbs went from .214 to .217, the sad thing is that for nearly 4h my devices behave very inconsistent, but that also 
by using the app or even the physical switches.

Any one else experiencing this?

[
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159693-TRADFRI-bulb-ws-1.2.217.ota.ota.signed",
        "fw_file_version_LSB": 30066,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 173246,
        "fw_image_type": 8705,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/190579-ncp572b444.ebl.ota.ota.signed",
        "fw_build_version": 444,
        "fw_file_version_LSB": 444,
        "fw_file_version_MSB": 5720,
        "fw_filesize": 166270,
        "fw_hotfix_version": 2,
        "fw_image_type": 2,
        "fw_major_version": 5,
        "fw_manufacturer_id": 4476,
        "fw_minor_version": 7,
        "fw_type": 1
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159694-TRADFRI-bulb-ws-gu10-1.2.217.ota.ota.signed",
        "fw_file_version_LSB": 30066,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 173246,
        "fw_image_type": 8707,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159695-TRADFRI-bulb-ws-1000lm-1.2.217.ota.ota.signed",
        "fw_file_version_LSB": 30066,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 173246,
        "fw_image_type": 8706,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159696-TRADFRI-bulb-w-1000lm-1.2.214.ota.ota.signed",
        "fw_file_version_LSB": 17778,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 168318,
        "fw_image_type": 8449,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159697-TRADFRI-driver-hp-1.2.217.ota.ota.signed",
        "fw_file_version_LSB": 30066,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 173246,
        "fw_image_type": 16898,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159698-TRADFRI-driver-lp-1.2.217.ota.ota.signed",
        "fw_file_version_LSB": 30066,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 173246,
        "fw_image_type": 16897,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159699-TRADFRI-remote-control-1.2.214.ota.ota.signed",
        "fw_file_version_LSB": 17778,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 158590,
        "fw_image_type": 4545,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159700-TRADFRI-motion-sensor-1.2.214.ota.ota.signed",
        "fw_file_version_LSB": 17778,
        "fw_file_version_MSB": 4641,
        "fw_filesize": 157822,
        "fw_image_type": 4548,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/159701-TRADFRI-wireless-dimmer-1.2.248.ota.ota.signed",
        "fw_file_version_LSB": 34162,
        "fw_file_version_MSB": 4644,
        "fw_filesize": 172926,
        "fw_image_type": 4546,
        "fw_manufacturer_id": 4476,
        "fw_type": 2
    },
    {
        "fw_binary_url": "http://fw.ota.homesmart.ikea.net/Tradfri_OTA_release_signed_2017_07_12_161101/bin/190578-TRADFRI-gateway-1.1.0015.p.elf.sig.ota.signed",
        "fw_filesize": 454588,
        "fw_hotfix_version": 15,
        "fw_major_version": 1,
        "fw_minor_version": 1,
        "fw_req_hotfix_version": 16,
        "fw_req_major_version": 9,
        "fw_req_minor_version": 9,
        "fw_type": 0,
        "fw_update_prio": 5,
        "fw_weblink_relnote": "https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html"
    }
]

**Comment by ghost** [comment]
They are rolling out a new software update which enables support for Apple HomeKit and other smart home management systems. [More information.](https://www.reddit.com/r/apple/comments/6ssb3x/ikeas_trådfri_now_supports_homekit/)

**Comment by hvanderlaan** [comment]
I've tested the source againts the new firmware, every function is working correctly over here. But as @trauta is mentioning the IKEA team is working on intergation of their tradfri into iOS and other smarthome managers.
