### ISSUE TITLE
Failure after gateway firmware update

### ISSUE THREAD

**Issue by rikardkjell** [hvanderlaan/ikea-smartlight#17]
After yesterdays update of the gateway firmware the scripts doesn't work for me any more...
Can supply information regarding error messages later on but for now this notification as a friendly alert from a otherwise happy user :-)
/R

**Comment by skatsikeas** [comment]
On the same page, here are some information about the changes made on the API with this latest update:
https://pbs.twimg.com/media/DNeWn9WXkAI4R6b.png

**Comment by hvanderlaan** [comment]
This is correct,

Ikea has change the way to connect to the gateway. Now you need to register a identity and with the code under the gateway (securityid) you well get a pre shared key.

I will update the code for this later today or in de evening.

**Comment by skatsikeas** [comment]
I have also an offtopic question about your implementation. Was your solution working with the version 1.0.0008 of the gateway or only with version 1.1.15? (I am asking becuase after yesterday's update I was forced to do a gateway reset and it reverted back to 1.0.0008...)

**Comment by hvanderlaan** [comment]
@sotos183 The current version should work under the older gateway I've completed the fix for gateway version 1.1.15 and will test it later today en push it to master.

**Comment by skatsikeas** [comment]
I think I have confused you with my question above :/, sorry about that.
The latest version, that introduced the PSK, is the 1.2.42 and not the 1.1.15

**Comment by hvanderlaan** [comment]
Oke, but i've tested it on 1.1.15 and that works as well with psk.

**Comment by skatsikeas** [comment]
Okay, then!
(Right now my gateway is stuck on 1.0.0008 after the reset and I cannot find a way to update it again - it says it is already up to date - so I cannot test it)

**Comment by hvanderlaan** [comment]
Ok that's not convenient. you should properly factory reset the gw.

Thank for the issues but i'm closing it for now
