### ISSUE TITLE
Tradfri Gateway Version 1.3.14 json errors

### ISSUE THREAD

**Issue by vanesp** [hvanderlaan/ikea-smartlight#33]
When I've set-up tradfri.cfg and I run the command ./tradfri-status.py I get the following error messages:

`[ ] Tradfri: acquiring all Tradfri devices, please wait ...  
Traceback (most recent call last):  
  File "./tradfri-status.py", line 101, in <module>  
    main()  
  File "./tradfri-status.py", line 52, in main   
    devices = tradfriStatus.tradfri_get_devices(hubip, apiuser, apikey)  
  File "/home/vanesp/ikea-smartlight/tradfri/tradfriStatus.py", line 46, in tradfri_get_devices  
    return json.loads(result.read().strip('\n').split('\n')[-1])  
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads  
    return _default_decoder.decode(s)  
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode  
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode  
    raise ValueError("No JSON object could be decoded")  
ValueError: No JSON object could be decoded`  

When I issue the coap command

`coap-client -m get -u "IDENTITY" -k "<key>" "coaps://192.168.2.2:5684/15001/65537"`

I get the following output:

`{"9003":65537,"9001":"keukenkastjes","9002":1527787087,"5750":2,"9020":1528315461,"9054":0,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI transformer 30W","2":"","3":"1.2.245","6":1},"3311":[{"5850":1,"5851":55,"9003":0}]}`

Hope you can help

**Comment by hvanderlaan** [comment]
Hey Peter,

This is because the script was created for the ikea smart lights only. When I'm not mistaking you are trying to use this also for the socket switches. I have not yet implemented this in the script.

I will see if i can find the device and update the script. 

Thanks for the mention of the bug
