### ISSUE TITLE
Creating preshared key

### ISSUE THREAD

**Issue by ipatiris** [hvanderlaan/ikea-smartlight#38]
My gateway has 1.9.27 firmware. I am trying to create a preshared key without a success. Can you please let me know what is the api user id? As security code I have put the code found in Gateway. As ip address I have gateways ip adress. What is the client identity?

**Comment by vandenberghev** [comment]
My hub completely hung after the update. You might want to power cycle it and give it another try.

**Comment by ipatiris** [comment]
In coap client there is ”Client_Identity”,”SECURITY_CODE” , ”IDENTITY” and ”IP_ADDRESS”. I have replaced the ”IP_ADDRESS” with my gateways ip. I have also replaced the ”SECURITY_CODE” with code found in gateway.  What are the remaining ”IDENTITY” and ”Client_Identity”. What I habe to put instead. What is the api user? Sorry for the noob question.

**Comment by hvanderlaan** [comment]
sorry for the short answer, but read the readme
